name: Build Shopware Plugin

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Shopware CLI
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/friendsofshopware/stable/setup.deb.sh' | sudo -E bash
          sudo apt-get update
          sudo apt-get install -y shopware-cli
          shopware-cli --version

      - name: Package plugin (zip)
        run: |
          shopware-cli extension zip "./ProductSliderHero"
          ls -la

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ProductSliderHero-dist
          path: "*.zip"

  attach-to-release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ProductSliderHero-dist
          path: dist
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip

